environment:
  BOT_TOKEN: "${BOT_TOKEN}"
  CHANNEL_ID: "${CHANNEL_ID}"
  OWNER_IDS: "${OWNER_IDS}"
  WEBHOOK_SECRET: "${WEBHOOK_SECRET}"

packages:
  - name: tg
    functions:
      - name: publish
        runtime: "go:default"
        web: true
        limits:
          timeout: 10000
          memory: 256
          logs: 32