environment:
  BOT_TOKEN: ${BOT_TOKEN}
  CHANNEL_ID: ${CHANNEL_ID}
  OWNER_IDS: ${OWNER_IDS}
  WEBHOOK_SECRET: ${WEBHOOK_SECRET}
  LOGGER_TOKEN: ${LOGGER_TOKEN}
  LOG_DESTINATIONS: ${LOG_DESTINATIONS}
  INGESTING_HOST: ${INGESTING_HOST}
  MINI_APP_URL: ${MINI_APP_URL}

packages:
  - name: tg
    functions:
      - name: publish
        runtime: go:1.20
        web: raw
        limits:
          timeout: 10000
          memory: 256
          logs: 32