name: frostcourse
region: fra
ingress:
  rules:
    - component: { name: api }
      match: { path: { prefix: / } }
    - component: { name: publish }    # имя компонента из секции functions
      match: { path: { prefix: /tg } }

services:
  - name: api
    github:
      repo: arty-ms/frostcourse-go
      branch: master
      deploy_on_push: true
    source_dir: .
    dockerfile_path: ./Dockerfile
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1

functions:
  - name: publish
    github:
      repo: arty-ms/frostcourse-go
      branch: master
      deploy_on_push: true
    source_dir: packages
    envs:
      - key: BOT_TOKEN
        scope: RUN_AND_BUILD_TIME
        value: ${POSTER_BOT_TOKEN}